package com.itmo.spy_system.entity;

public enum NotificationType {
    CONTRACT_CREATION, CONTRACT_STATUS_UPDATE, PUNISHMENT_TASK_CREATION, DEVICE_CHANGE_TASK_CREATION, TASK_CANCELLED,
    NEW_CLIENT_ASSIGNED, DEVICE_OFF, DEVICE_INACTIVE, DEVICE_LOW_BATTERY, CONTRACT_OUTDATED
}
